version: "6"
services:
   ansible:
     container_name: ansible
     image: ansible
     tty: true
     stdin_open: true
     build: 
       context: ./
     networks:
       - datacenter
     volumes:
       - ./ansible:/root/ansible       
   remote_one: 
     container_name: remote-one
     image: remote-host
     build: 
       context: ./remote-hosts
     networks:
       - datacenter
   remote_two:
     container_name: remote-two
     image: remote-host
     build: 
       context: ./remote-hosts
     networks:
       - datacenter
networks:
  datacenter:
volumes:
  ansible:
